### ISSUE TITLE
Integrate Ansible

### ISSUE THREAD

**Issue by jloeser** [openSUSE/orthos2#14]
Let's discuss about integrating Ansible in Orthos.

I think Ansible (https://docs.ansible.com/) would perfectly fit into Orthos and could partly (or even full?) replace Orthos' task functionality (https://github.com/openSUSE/orthos2/tree/master/orthos2/taskmanager/tasks). 

Instead of reinventing the wheel and doing all by hand (connect to remote host, execute script, collect result) we should think of utilizing Ansible for those jobs. It's very likely that there are already modules we can use for e.g. collecting all relevant machine information. If not we could even provide own Ansible modules for this.

What's the opinion on this from you guys?

**Comment by Conan-Kudo** [comment]
This sounds great. It would make it much easier to integrate a wider variety of existing stuff to support developer systems management.

**Comment by jloeser** [comment]
Let's do some brainstorming:

- we do need Ansible available on the server
- collecting machine information requires machines which are (obviously):
  - online (physically up, ping)
  - run Linux
  - allow login via ssh (best with pubkey)
  - have Python installed
- Orthos collects machine information:
  - for a set of machines every night (use Ansible's inventory?)
  - for a single machine after it has been added to Orthos
- we could use Ansible to also check for login/abuild
  - is abuild check still required btw.?
- Orthos would call something like ``ansible-playbook -i <all|single machine> playbook.yml`` and returns e.g. JSON with results
  - results needs to be processed (error cases, actual data needs to go into database)
  - Ansible playbooks and Orthos needs to be geared to each other in order to have common understanding of the keys/values reported by Ansible in order to let Orthos store them in database

If developer would like to extend things they need to provide both, playbooks and corresponding Orthos code. However we could cut down codebase of Orthos and make it less error-prone thinking of the part doing remote code execution and the functions collecting all this HW information. I personally like the idea to open Orthos for established tools and have more interfaces instead of self-made code.

**Comment by SchoolGuy** [comment]
@jloeser If we go that far wouldn't we mutate Orthos2 just into a collection of Ansible scripts with a frontend for people who don't know Ansible? I mean I don't have something against it but I am just curious where we go from there. Orthos also is (afaik) already making use of Cobbler for some things, thus reducing the tasks Orthos2 is doing on its own even further.

**Comment by jloeser** [comment]
> @jloeser If we go that far wouldn't we mutate Orthos2 just into a collection of Ansible scripts with a frontend for people who don't know Ansible?

At the end every tool is "just" an additional layer utilizing existing tools/frameworks/technologies under the hood, if you want to see it like this. I don't see this as a drawback.


> I mean I don't have something against it but I am just curious where we go from there. Orthos also is (afaik) already making use of Cobbler for some things, thus reducing the tasks Orthos2 is doing on its own even further.

I see Orthos a) as source of truth for all the data and b) who decides when to do what. The execution should be done by somebody who exclusively does it and who does it well (one of the Unix/Linux principles). Isn't that also the reason why utilizing Cobbler?

In addition it (c provides a nice interface to the users and administrators (thinking of web/cli) plus the whole reservation system what I see as a unique selling point.

**Comment by SchoolGuy** [comment]
Yes in the end every tool is just another layer. I agree with that but that layer provides a feature which makes it reasonable to use it. And if we are in the end Ansible + Webinterface, then I think it would be best to just run AWX (https://github.com/ansible/awx) and optimize the playbooks for it. Orthos is a pretty complex and huge thing. Every line of code we don't have to care about is a good line in my eyes.

A source of truth is Orthos also not since the location data is coming from Racktables and the MAC <--> IP relations are managed in Cobbler (since it provisions the DHCP server). Reinstallation is done via network boot which is also Cobbler managed. Power management is included in Cobbler, so also not unique and already there. The serial console stuff is nice and neat but it also is partly integrated in Cobbler already as far as I know.

Sadly the unique point with the reservation system is not as unique as I also has thought. Cobbler has that, although I have to admit not as advanced as Orthos2 possibly.

The point with the nice interface for users and admins I agree fully with that is better then Cobbler and Orthos1. I had a discussion with @watologo1 about this already and the featureset of Orthos2 and Cobbler definitely have big overlaps and I would like to reduce them to make them work better together instead of having to maintain the same functionality two times. This is also valid for Ansible since Cobbler has also an official Ansible Playbook contributed from the community.

So for what IS Orthos2 currently the source of truth?

- In my eyes it just collects data it gets from various points and renders that nicely.
- It collects the hardware information and displays that

And thats it as far as I could look through the codebase.

**Comment by SchoolGuy** [comment]
I am sorry if that sounded somehow like I want to get rid of Orthos2. It is not my intention, I am just very concerned about running in a direction which brings us little advantages and needs many efforts to be maintained...

**Comment by jloeser** [comment]
> And if we are in the end Ansible + Webinterface, ...

... + sophisticated cron job :see_no_evil: Btw. I never worked with AWX or Ansible Tower before, if I find time I will look at it.

> I am just very concerned about running in a direction which brings us little advantages and needs many efforts to be maintained...

Why is it more effort to maintain on the long run? Ok, there is work to do once integrating the interface, cutting down Orthos and move functionality from Orthos to Ansible playbooks, etc. but afterwards I would expect to even have less maintenance work.

> A source of truth is Orthos also not since the location data is coming from Racktables and the MAC <--> IP relations are managed in Cobbler (since it provisions the DHCP server). Reinstallation is done via network boot which is also Cobbler managed. ...

Please have in mind that Orthos - now as it is published - may also be used outside of SUSE infrastructure which may have no such services serving as information source and where Orthos is the boss (as it was also for Orthos1 for the one or other dataset back in the days) I really would like to introduce it at my current company's infrastructure for managing SOCs which is some slightly other use case regarding the hardware to-be-maintained and for example the software deployment. Therefor I won't use Cobbler at all and I am not forced to use it to run Orthos, which is cool. Still I want to manage multiple enclosures with machines etc. That's where I think Orthos would fit perfectly.. if we can upgrade it a bit :smiley:

Honestly I am not sure when it's time to stop extending one tool and better start using another. I know that there are some overlaps currently but that must not be in all circumstances.

> I am sorry if that sounded somehow like I want to get rid of Orthos2.

Nah, don't worry - good that we have such discussions here!

**Comment by SchoolGuy** [comment]
I also have never worked with Ansible and/or AWX but it seems reasonable to at least have a look.

Rearding the maintenance: Well this is a Django Project and Django has with every version now and then breaking changes. Since every change on the business layer side (which is Django unrelated I guess), needs adjustments on the CLI and Webinterface, we need to address them.

Okay I was not aware of the fact that it is possible to run Orthos without Cobbler and/or Racktables. So we maybe need to extend our docs. Should I open an issue to port the docs to rst with Sphinx and build them on rtd? Then we could document everything there - which would be an improvement over the few lines we now have just in Git.

**Comment by jloeser** [comment]
> Okay I was not aware of the fact that it is possible to run Orthos without Cobbler and/or Racktables.

At least this test instance I run works without Cobbler - I mean ok, then you can't power cycle or do network boot obviously. But that's the degree of freedom I want to have: Is Cobbler available and configured -> use it; if I don't have I want at least have the option to trigger *) any script/tool/you-name-it without the need to touch Orthos code. If I reserve a machine in Orthos I want to have the option to do things according to my needs on the target the default by Orthos doesn't fit my expectations.

> So we maybe need to extend our docs. Should I open an issue to port the docs to rst with Sphinx and build them on rtd? Then we could document everything there - which would be an improvement over the few lines we now have just in Git.

Yeah, please go ahead. We really lack of good documentation! That's btw. also something I neglected a bit. But having such an online documentation thingy in place would be really nice (like all the other cool projects have).

*) Next point I have in mind: what's about using a standardized messaging protocol like amqp for signaling events happening in Orthos like e.g. OBS does it (https://rabbit.opensuse.org/)?

**Comment by SchoolGuy** [comment]
- So the issue was created (#22) and I will start on this later. It is not much to do but I need to sit down and do it.
- Regarding the flexibility of Orthos2 I find that pretty good. Documentation is everything.
- Regarding the messaging protocol: I have no opinions on that, I don't have that much time sadly to work on Orthos that deep.

**Comment by watologo1** [comment]
> So for what IS Orthos2 currently the source of truth?

- The command line client, specifically the query tool/command
  This one allows to search in a very complex way over thousands of data in ms.
- The fact that cobbler stores everything in these json collections is not nice, it results in:
  * being very slow
  * hard to do backups
- Cobbler is what I've heard racy..., orthos is well tested with hundreds of machines.
  While we want to have this fixed in cobbler, orthos can even be used to serialize things...

Just some arguements why things are as they are...

**Comment by jloeser** [comment]
Regarding signaling events in Orthos see #23

**Comment by watologo1** [comment]
Done.
See:
commit 1ad3affbb54e10394c3c61cab72e038759a8e2cc
    Basic ansible enablement
commit f388f09ed8b9f62034f3eb61419e2000b0fd076b
    Ansible implementation for miscellaneous and pci_devices data scans
commit b0681b337fe21b19315e9c71d6dfa0047eb63d33
    Lots of ansible enhancements
