### ISSUE TITLE
Setup machine UI misleading

### ISSUE THREAD

**Issue by olafhering** [openSUSE/orthos2#162]
The `Setup Machine` button in the webui opens another window. Therefore it needs three trailing dots.
The `Start Setup` button in the webui executes the setup instantly. Therefore it must not have three trailing dots.

**Comment by SchoolGuy** [comment]
@olafhering I tried to reproduce this bug just now. For me,

- the `Setup Machine` button opens the new page in the same window.
- the `Start Setup` button doesn't have three dots.

Could you maybe attach screenshots that show what you mean in more detail? Otherwise, I would like to close this issue as invalid.

**Comment by olafhering** [comment]
This was addressed with `bug#1194812`.
