### ISSUE TITLE
add bmc fails

### ISSUE THREAD

**Issue by olafhering** [openSUSE/orthos2#176]
It is unclear how add bmc is supposed to be used:
````
add machine
...
(orthos 2.0.0:olh) add bmc
ERROR: Invalid number of arguments for 'bmc'!
````
`help add` does not explain `bmc`

**Comment by olafhering** [comment]
Maybe it is like this:
````
(orthos 2.0.0:olh) add bmc FQDN
ERROR: HTTP Error 500: Internal Server Error (https://orthos2.arch.suse.de:443/api)
Good bye, have a lot of fun...
````

**Comment by SchoolGuy** [comment]
The bugfix in #209 cannot be tested in our CI atm since `REMOTEPOWER_TYPES` is statically defined in `settings.py`. Since model fields are class-based variables the choices for the `fence_name` is set during the load of the `remotepowerdevice.py`. This makes it impossible/impractical to manipulate during runtime.

The solution for such dynamic values are according to several Django Forum posts I read to convert this static array into a model and switch the choices into a queryset.
