### ISSUE TITLE
SSH-Public-Key-Support in Orthos – Input & LDAP-Synchronisation

### ISSUE THREAD

**Issue by faeller** [openSUSE/orthos2#223]
The Slack channel and specifically @olafhering about Orthos and Thomas inspired me: Folks who frequently work with SSH keys, like myself, thought it would be super handy if Orthos had the ability to store SSH public keys and synchronize them with LDAP. Here are the basic ideas:

    Store SSH Keys in Orthos: Let's create a simple way to add or delete SSH public keys in Orthos settings.
    LDAP Synchronization: How about having these keys automatically synchronized with an LDAP directory? It could make access control management easier.
    Django Integration: Since Orthos runs on Django, it should fit seamlessly into the user interface.

I believe these features could make Orthos even more useful. I'd love to hear your thoughts on this!

-------

German Version:

Der Slack-Channel zu Orthos & Thomas haben mich dazu inspiriert: Leute die häufig arbeiten mit SSH-Schlüsseln und dachte, es wäre super praktisch, wenn Orthos die Möglichkeit hätte, SSH-öffentliche Schlüssel zu speichern und mit LDAP zu synchronisieren. Hier sind die Grundideen:

    SSH-Keys in Orthos speichern: Lasst uns eine einfache Möglichkeit schaffen, SSH-öffentliche Schlüssel in den Orthos-Einstellungen hinzuzufügen oder zu löschen.
    LDAP-Synchronisation: Wie wäre es, wenn diese Schlüssel automatisch mit einem LDAP-Verzeichnis synchronisiert würden? Das könnte die Verwaltung der Zugriffsberechtigungen erleichtern.
    Django-Integration: Da Orthos auf Django läuft, sollte es sich nahtlos in die Benutzeroberfläche einfügen.

Ich glaube, dass diese Features Orthos noch nützlicher machen könnten. Würde mich über eure Gedanken dazu freuen
!

**Comment by SchoolGuy** [comment]
@faeller Great to have you back from school. Please translate it to English so we keep all issues in the same language.

To the idea itself... We shouldn't add a feature this big to Orthos. All remaining development should go into bugfixing please. After that let's please look at the migration to a pure Cobbler stack.

**Comment by faeller** [comment]
> @faeller Great to have you back from school. Please translate it to English so we keep all issues in the same language.
> 
> To the idea itself... We shouldn't add a feature this big to Orthos. All remaining development should go into bugfixing please. After that let's please look at the migration to a pure Cobbler stack.

works for me, I'm working on https://github.com/faeller/wicked-autocomplete

**Comment by faeller** [comment]
@watologo1

**Comment by olafhering** [comment]
I think the LDAP server should allow some sort of self-service to store the personal ssh pubkey.
Then a simple script can retrieve this key and append it to ~root/.ssh/authorized_keys. That simple script will run during deployment. And everyone else interested can obtain the key as needed.

In other words, there is nothing specific about orthos in this idea. orthos deployment would be just another consumer of the data.

**Comment by SchoolGuy** [comment]
@olafhering This is the first matter that is giving me goosebumps. Why should one append this for `root`. Using a user here would be a lot more reasonable since there is no need for everyone to be root on any system deployed there. This needs to be integrated into Cobbler in some sort as well as Cobbler needs to read the keys. As such this "simple script" will very fast get out of hand as it has many implications that if we use it internally needs to be discussed with security.

**Comment by olafhering** [comment]
Right, it does not need to be ~root. Since sssd is properly configured, everyone should be able to login already today. Well, except the ones who do not have an account backed by sssd, in case such orthos users exist. And of course except the machines which do have sssd properly running, but can not possibly reach the shared storage for the ldap user.

I guess the "script" is a simple ldap-client call to obtain some data.

Perhaps the deployment needs to create a common local user, and store the retrieved key there.

**Comment by olafhering** [comment]
In addition I think the login already works today, even if the shared storage can not be reached. There is a pam module which creates the ldap user $HOME on-demand.

**Comment by olafhering** [comment]
Are the deployment scripts stored in this repo? Likely not, so not strictly an orthos issue. Rather a to-be-added functionality for these scripts.

**Comment by SchoolGuy** [comment]
@olafhering I'll keep this issue open for tracking purposes. Thanks for raising it.

**Comment by SchoolGuy** [comment]
So since internally at SUSE there is now a plan to provide a directory service that offers self-service for adding SSH keys and this feature is rather big for Orthos, I believe we can close this. The idea is very good but I have no resources to implement a feature like this as previously mentioned already.
